language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TEST=ci
  - TEST=plugin SQ_VERSION=DEV
  - TEST=plugin SQ_VERSION=LATEST_RELEASE
  - TEST=plugin SQ_VERSION=LTS
matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
